apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: python-backend
  ports:
    - protocol: TCP
      port: 8000          # The port exposed by the service
      targetPort: 8000    # The port on which the python backend API listens
  type: NodePort
