apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-frontend
  template:
    metadata:
      labels:
        app: nuxt-frontend
    spec:
      containers:
        - name: nuxt-container
          image: nuxt-frontend:dev
          ports:
            - containerPort: 3000
