apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-frontend
  template:
    metadata:
      labels:
        app: nuxt-frontend
    spec:
      containers:
        - name: frontend-container
          image: nuxt-frontend-dev # TODO: should i mby change skaffold.yaml to this?
          env:
          - name: API_BASE_URL
            value: "http://backend-service:8000"
          ports:
            - containerPort: 3000
