apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: nuxt-frontend
  ports:
    - protocol: TCP
      port: 3000          # The port exposed by the service
      targetPort: 3000  # The port on which the nuxt app listens
  type: NodePort
